-- TEST DATA for the lot trace and recall workspace. NOT a migration - run by hand, removed by delete.sql.
-- Every row carries data._test_batch = 'RECALL-TEST', every lot starts TEST- or is 9901 / 9902 (no real lot code
-- has a day above 366), and every product and customer starts with TEST.
-- Retention (FRM-703) and release (FRM-701) go in as DRAFTS: submitted ones would tick off the weekly
-- retention and release review reminders on the verification schedule. Test FRM-801 dispatches are dated
-- before the real one of 2026-10-01, so the dispatch review is not affected either.

begin;

do $guard$
begin
  if exists (select 1 from public.sop_document_responses where data->>'_test_batch' = 'RECALL-TEST') then
    raise exception 'Recall test data is already there - run delete.sql first.';
  end if;
end $guard$;

insert into public.sop_document_responses
  (document_id, form_number, form_revision, data, status, created_by, created_at, submitted_at, submitted_by)
select d.id, d.sop_number, d.revision, v.data, v.status, '5eea644d-d8d3-4ad3-a55a-ef391334432d'::uuid, v.at,
       case when v.status = 'submitted' then v.at end, case when v.status = 'submitted' then '5eea644d-d8d3-4ad3-a55a-ef391334432d'::uuid end
from (values
  ('FRM-301', 'submitted', '2026-09-15T14:00:00Z'::timestamptz, $j${"receiving_log": [{"time_of_arrival": "09:10", "po_number": "TEST-PO", "supplier_name": "TEST Sysco", "brand_manufacturer": "TEST Brand", "material_description": "TEST Soybean Oil (35 lb jug)", "lot_batch_number": "TEST-SO-1001", "carrier_name_seal": "TEST carrier", "qty_received": 4, "net_weight": "140 lb", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}, {"time_of_arrival": "09:10", "po_number": "TEST-PO", "supplier_name": "TEST Sysco", "brand_manufacturer": "TEST Brand", "material_description": "TEST Liquid Eggs (30 lb jug)", "lot_batch_number": "TEST-EG-2001", "carrier_name_seal": "TEST carrier", "qty_received": 2, "net_weight": "60 lb", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}, {"time_of_arrival": "09:10", "po_number": "TEST-PO", "supplier_name": "TEST Sysco", "brand_manufacturer": "Pillsbury", "material_description": "TEST Creme Cake Mix (50 lb bag)", "lot_batch_number": "TEST-CM-3001", "carrier_name_seal": "TEST carrier", "qty_received": 6, "net_weight": "300 lb", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}, {"time_of_arrival": "09:10", "po_number": "TEST-PO", "supplier_name": "TEST Packaging Co", "brand_manufacturer": "", "material_description": "TEST Film roll", "lot_batch_number": "TEST-FILM-01", "carrier_name_seal": "TEST carrier", "qty_received": 1, "net_weight": "1 roll", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}], "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-301', 'submitted', '2026-09-19T14:00:00Z'::timestamptz, $j${"receiving_log": [{"time_of_arrival": "10:30", "po_number": "TEST-PO", "supplier_name": "TEST Sysco", "brand_manufacturer": "TEST Brand", "material_description": "TEST Soybean Oil (35 lb jug)", "lot_batch_number": "TEST-SO-1002", "carrier_name_seal": "TEST carrier", "qty_received": 2, "net_weight": "70 lb", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}, {"time_of_arrival": "10:30", "po_number": "TEST-PO", "supplier_name": "TEST Flavor Co", "brand_manufacturer": "", "material_description": "TEST Coconut flavor", "lot_batch_number": "TEST-FL-4001", "carrier_name_seal": "TEST carrier", "qty_received": 1, "net_weight": "1 gal", "carrier_cleanliness": "pass", "pkg_integrity_damage": "pass", "approved_supplier_coa_log_coc": "pass", "receiver_initals": "RM", "comments_hold_status": "TEST DATA"}], "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-520', 'submitted', '2026-09-22T14:00:00Z'::timestamptz, $j${"product": "TEST Rum Cake Original", "lot_code": "9901", "bake_date": "2026-09-22", "batches": 1, "ingredients": [{"ingredient": "Soybean Oil (35 lb jug)", "brand": "TEST Brand", "supplier_lot": "test so 1001", "expected_qty": 17.49, "unit": "lb", "actual_qty": 17.49, "notes": ""}, {"ingredient": "Liquid Eggs (30 lb jug)", "brand": "TEST Brand", "supplier_lot": "TEST-EG-2001", "expected_qty": 13.49, "unit": "lb", "actual_qty": 13.49, "notes": ""}, {"ingredient": "Creme Cake Mix (50 lb bag)", "brand": "Pillsbury", "supplier_lot": "TEST-CM-3001", "expected_qty": 49.97, "unit": "lb", "actual_qty": 49.97, "notes": ""}, {"ingredient": "Baking powder", "brand": "", "supplier_lot": "TEST-BP-5001", "expected_qty": 0.25, "unit": "lb", "actual_qty": 0.25, "notes": ""}, {"ingredient": "Water", "brand": "", "supplier_lot": "City water - no lot", "expected_qty": 7.99, "unit": "lb", "actual_qty": 7.99, "notes": ""}, {"ingredient": "Pan release spray (contains soy)", "brand": "", "supplier_lot": "", "expected_qty": 0, "unit": "each", "actual_qty": 0, "notes": ""}], "rework": "No rework used", "pack_date": "2026-09-22", "units_packed": "120 units", "film_lot": "TEST-FILM-01", "code_check": "Matches the lot code above", "packing_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-520', 'submitted', '2026-09-22T14:00:00Z'::timestamptz, $j${"product": "TEST Coconut Rum Cake", "lot_code": "9901", "bake_date": "2026-09-22", "batches": 1, "ingredients": [{"ingredient": "Soybean Oil (35 lb jug)", "brand": "TEST Brand", "supplier_lot": "TEST-SO-1001", "expected_qty": 8.75, "unit": "lb", "actual_qty": 8.75, "notes": ""}, {"ingredient": "Creme Cake Mix (50 lb bag)", "brand": "Pillsbury", "supplier_lot": "TEST-CM-3001", "expected_qty": 25, "unit": "lb", "actual_qty": 25, "notes": ""}, {"ingredient": "Coconut flavor", "brand": "TEST Flavor Co", "supplier_lot": "TEST-FL-4001", "expected_qty": 0.5, "unit": "lb", "actual_qty": 0.5, "notes": ""}], "rework": "No rework used", "pack_date": "2026-09-22", "units_packed": "60 units", "film_lot": "TEST-FILM-01", "code_check": "Matches the lot code above", "packing_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-520', 'draft', '2026-09-24T14:00:00Z'::timestamptz, $j${"product": "TEST Rum Cake Original", "lot_code": "9902", "bake_date": "2026-09-24", "batches": 1, "ingredients": [{"ingredient": "Soybean Oil (35 lb jug)", "brand": "TEST Brand", "supplier_lot": "TEST-SO-1001", "expected_qty": 5, "unit": "lb", "actual_qty": 5, "notes": ""}, {"ingredient": "Soybean Oil (35 lb jug)", "brand": "TEST Brand", "supplier_lot": "TEST-SO-1002", "expected_qty": 12.49, "unit": "lb", "actual_qty": 12.49, "notes": ""}, {"ingredient": "Liquid Eggs (30 lb jug)", "brand": "TEST Brand", "supplier_lot": "TEST-EG-2001", "expected_qty": 13.49, "unit": "lb", "actual_qty": 13.49, "notes": ""}, {"ingredient": "Creme Cake Mix (50 lb bag)", "brand": "Pillsbury", "supplier_lot": "TEST-CM-3001", "expected_qty": 49.97, "unit": "lb", "actual_qty": 49.97, "notes": ""}], "rework": "No rework used", "pack_date": "2026-09-24", "units_packed": "100 units", "film_lot": "TEST-FILM-01", "code_check": "Matches the lot code above", "packing_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-801', 'submitted', '2026-09-25T14:00:00Z'::timestamptz, $j${"dispatch_date": "2026-09-25", "customer": "TEST Island Treats LLC", "carrier": "Customer's own vehicle", "vehicle_id": "TEST-VAN", "loaded": [{"product": "TEST Rum Cake Original", "lot_code": "9901", "quantity": "80 units", "released": "pass"}, {"product": "TEST Coconut Rum Cake", "lot_code": "9901", "quantity": "60 units", "released": "pass"}], "checks": [{"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}], "vehicle_accepted": "Accepted — loaded", "pallets_wrapped": "pass", "weather_ok": "pass", "apron_clear": "pass", "not_on_ground": "pass", "load_secured": "pass", "compartment_secured": "pass", "loading_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-801', 'submitted', '2026-09-26T14:00:00Z'::timestamptz, $j${"dispatch_date": "2026-09-26", "customer": "TEST Gift Basket Co", "carrier": "Customer's own vehicle", "vehicle_id": "TEST-VAN", "loaded": [{"product": "TEST Rum Cake Original", "lot_code": "9901", "quantity": "3 cases", "released": "pass"}], "checks": [{"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}], "vehicle_accepted": "Accepted — loaded", "pallets_wrapped": "pass", "weather_ok": "pass", "apron_clear": "pass", "not_on_ground": "pass", "load_secured": "pass", "compartment_secured": "pass", "loading_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-801', 'draft', '2026-09-27T14:00:00Z'::timestamptz, $j${"dispatch_date": "2026-09-27", "customer": "TEST Island Treats LLC", "carrier": "Customer's own vehicle", "vehicle_id": "TEST-VAN", "loaded": [{"product": "TEST Rum Cake Original", "lot_code": "9902", "quantity": "40 units", "released": "pass"}], "checks": [{"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}], "vehicle_accepted": "Accepted — loaded", "pallets_wrapped": "pass", "weather_ok": "pass", "apron_clear": "pass", "not_on_ground": "pass", "load_secured": "pass", "compartment_secured": "pass", "loading_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-703', 'draft', '2026-09-22T14:00:00Z'::timestamptz, $j${"product_name": "TEST Rum Cake Original", "lot_code": "9901", "customer": "TEST Island Treats LLC", "date_produced": "2026-09-22", "date_taken": "2026-09-22", "pack_description": "1 sealed unit", "units_retained": 1, "printed_date": "September 2027", "discard_due": "2027-10-30", "storage_location": "TEST retention shelf", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-701', 'draft', '2026-09-23T14:00:00Z'::timestamptz, $j${"product_name": "TEST Rum Cake Original", "lot_code": "9901", "date_produced": "2026-09-22", "quantity_released": "120 units", "customer": "TEST Island Treats LLC", "checks": [{"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}, {"result": "pass", "note": ""}], "decision": "RELEASED — may be shipped, collected or transferred", "release_date": "2026-09-23", "release_notes": "TEST DATA", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-702', 'submitted', '2026-10-01T14:00:00Z'::timestamptz, $j${"hold_tag_number": "TEST-H-001", "date_time_placed_on_hold": "2026-10-01T09:00", "material_name_description": "TEST Soybean Oil (35 lb jug)", "supplier_name": "TEST Sysco", "supplier_lot_batch_number": "TEST-SO-1001", "total_quantity_placed_on_hold": "1 jug, part used", "detailed_description_of_issue": "TEST DATA - supplier recall notice for this lot (mock).", "_test_batch": "RECALL-TEST"}$j$::jsonb),
  ('FRM-011', 'submitted', '2026-09-01T14:00:00Z'::timestamptz, $j${"reviewed_on": "2026-09-01", "off_site_copy": "TEST", "contacts": [{"_label": "Senior Site Management", "group": "Crisis team", "name": "TEST Person A", "phone": "555-0101", "email": "", "when": "Recall coordinator - first call"}, {"_label": "SQF Practitioner", "group": "Crisis team", "name": "TEST Person B", "phone": "555-0102", "email": "", "when": "Trace, holds and investigation"}, {"_label": "SQFI", "group": "SQF", "name": "", "phone": "", "email": "foodsafetycrisis@sqfi.com", "when": "In writing within 24 hours"}, {"_label": "Certification body", "group": "SQF", "name": "", "phone": "", "email": "", "when": "In writing within 24 hours - to be added when contracted"}, {"_label": "FDA - recall coordinator / Reportable Food Registry", "group": "Authority", "name": "", "phone": "555-0110", "email": "", "when": "Recall; RFR report within 24 hours where serious harm is probable"}, {"_label": "FDACS Division of Food Safety", "group": "Authority", "name": "", "phone": "555-0111", "email": "", "when": "Recall or a crisis affecting the food permit"}, {"_label": "TEST Island Treats", "group": "Customer (brand owner)", "name": "Ana Test", "phone": "555-0100", "email": "ana@example.com", "when": "Any withdrawal or recall of their product"}], "_test_batch": "RECALL-TEST"}$j$::jsonb)
) as v(form, status, at, data)
join public.sop_documents d on d.sop_number = v.form and d.type = 'form' and d.status in ('active', 'draft');

do $verify$
begin
  if (select count(*) from public.sop_document_responses where data->>'_test_batch' = 'RECALL-TEST') <> 12 then
    raise exception 'Expected 12 test rows.';
  end if;
end $verify$;

commit;
