-- FSQM-039: redraw for a THREE-day rotation.
--
-- The drawing was built for two days, with everything after the bake on Day 2. Production has
-- confirmed the finishing work is split across two days:
--   Day 1  weigh, mix, deposit, bake, cool                  (unchanged)
--   Day 2  dunk in simple syrup, seal
--   Day 3  package, label, lot code, bulk packaging
-- The draw.io master now carries a third layer set (Sheet 3), and the owner has placed the Day 3
-- equipment. This brings the document's text into line with it.
--
-- TWO FACTS CAME WITH THE SPLIT, both from the owner (2026-09-18), and both are in the procedure:
--   * Sealed product is held overnight where the sealing unit stands on Day 2 - the sealer is moved
--     at the end of Day 2 and the product takes its place. Sheet 2's route therefore ends at the
--     sealer and the hold appears on Sheet 3 only.
--   * The weighing station is removed after Day 1. The previous text said it stood idle inside
--     HIGH CARE on Day 2 and defended that as a zoning decision; that was describing a floor that
--     does not exist, so the three lines are replaced rather than extended to Sheet 3.
--
-- STILL A DRAFT, STILL REVISION New. The document has never been issued, so this is an edit to the
-- draft rather than a revision - the same way 20260915000003 was. The sop_document_history trigger
-- only snapshots published rows, so nothing is lost that was ever in force.
--
-- ATTACHMENTS ARE NOT TOUCHED HERE. The record still holds the two old PDFs and the master; the
-- text now describes four files. They are replaced through the app (Reference Documents tab) once
-- the three sheets are exported, which is the owner's step and the one this change is not complete
-- without.
--
-- Merged with `content || ...` so attachments and governing_reference are preserved as they are.

begin;

do $guard$
declare st text; rev text; n int; p text;
begin
  select status, revision, jsonb_array_length(content->'procedure'), (content->'procedure')::text
    into st, rev, n, p
    from public.sop_documents where sop_number = 'FSQM-039';
  if st is null then raise exception 'FSQM-039 does not exist.'; end if;
  if (st, rev) is distinct from ('draft', 'New') then
    raise exception 'FSQM-039 is %/% - expected the unissued draft.', st, rev;
  end if;
  if n <> 27 or p not like '%issued as two sheets%' then
    raise exception 'FSQM-039 procedure is not the two-sheet text this replaces (% lines).', n;
  end if;
end $guard$;

update public.sop_documents
   set content = content || $patch${"scope": "The production floor of units 415 and 425, and the movement of product across it from the receipt of ingredients at the weighing station to the application of the lot code and bulk packaging. It covers all three configurations of the three-day rotation and issues one sheet for each.\n\nDELIBERATELY OUT OF SCOPE, and not to be read as omissions:\n\nPersonnel flow, hand-wash points and allergen segregation. This drawing answers two questions — where does equipment stand, and where does product go. Personnel movement is a different question with a different audience and a different review cycle, and drawing three overlays on one sheet makes all three harder to read. Where personnel flow across the raw / high-care boundary needs to be controlled, that is a matter for the GMP programme, and a personnel flow drawing is the right home for it if one is later required.\n\nThe process itself, which is governed by the relevant SOPs.\n\nThe food safety plan and its hazard analysis, and the flow diagram required by 2.4.3.6 — which this drawing is not. See the governing reference.", "records": "No records are generated by this document.\n\nThe document itself is the record: four files are held as attachments to this entry — Sheet 1 (Day 1), Sheet 2 (Day 2) and Sheet 3 (Day 3) as PDF, and the editable draw.io master from which all three sheets are exported. The master is in the Reference Documents tab of this record and is edited at app.diagrams.net; all three sheets are re-exported from it and all four attachments replaced together whenever it changes.\n\nSuperseded revisions are retained by the sop_document_history trigger, which snapshots the row whenever a watched field changes on a published document.", "definitions": "Sheet 1 (Day 1): the floor as configured for weighing, mixing, depositing and baking. The depositor and the weighing station are in the room.\n\nSheet 2 (Day 2): the floor as configured for dunking in simple syrup and sealing. The depositor and the weighing station have been removed and the dunk station occupies the depositor's bay.\n\nSheet 3 (Day 3): the floor as configured for packaging, labelling, lot coding and bulk packaging. The dunk station has been removed, the sealing unit has been moved, and the sealed product is held in the sealing unit's place.\n\nDunk bay: the bay that holds the depositor on Day 1 and the dunk station on Day 2. Its hygiene status is not the same on Day 1 as on Day 2.\n\nSealed product hold: where sealed product waits overnight between Day 2 and Day 3 — the position the sealing unit occupies on Day 2.\n\nScale: the drawing is to scale. One grid square is five feet.", "procedure": ["This drawing is issued as three sheets, one per day of the rotation, and all three sheets are part of the same document at the same revision.", "> Issuing one sheet would misrepresent the floor. The equipment in the room is different on each of the three days, so a single drawing would have to show either a configuration that exists a third of the time or a composite that exists never.", "> Sheet 1 carries steps 1 to 5 and the depositor. Sheet 2 carries steps 6 and 7 and the dunk station. Sheet 3 carries steps 8 and 9, the sealed product hold and the lot code printer. The sheet number and the day are printed on each.", "The floor is divided into six hygiene zones, and the kill step is the oven.", "• NON-PRODUCTION — offices and reception.", "• PACKAGING MATERIALS STORAGE.", "• RAW / PRE-BAKE [LOW RISK] — ingredients, and on Day 1 weighing, mixing and depositing.", "• BAKE [KILL STEP] — the two ovens.", "• COOLING [HIGH CARE] — the post-bake racks on the west wall.", "• HIGH CARE — dunking, sealing, packaging, labelling and lot coding.", "> Everything upstream of the oven is low risk and everything downstream of it is high care. That single division is what the zoning is for, and it is the thing an auditor will look for first.", "> The premises these zones divide are governed by FSQM-012.", "THE DUNK BAY CHANGES HYGIENE STATUS BETWEEN DAY 1 AND DAY 2. It holds raw batter on Day 1 and post-bake product on Day 2.", "> This is the consequence of the rotation and it is the most important thing on the drawing. The same floor area is low risk on one day and high care on the next, so what separates them is not a wall but the changeover clean performed between Day 1 and Day 2.", "> That places weight on the changeover being performed and recorded. A zoning that depends on a clean is only as good as the record that the clean happened.", "Day 2 and Day 3 are zoned identically.", "> Nothing on Day 3 returns the area to raw use, so its hygiene status does not change between the two days and the zoning does not depend on anything done between them. By Day 3 every unit is sealed, so no product is exposed on that day.", "Sealed product is held overnight between Day 2 and Day 3, in the position the sealing unit occupies on Day 2.", "> The sealing unit is moved at the end of Day 2 and the sealed product is held in its place. That is why the hold appears on Sheet 3 only, and why Sheet 2's product route ends at the sealer.", "The weighing station is in the room on Day 1 only.", "> It is removed after Day 1, so Sheets 2 and 3 do not show it, and on those sheets the RAW / PRE-BAKE zone is the bottom strip holding the ingredients.", "This drawing is not the flow diagram required by 2.4.3.6 and shall not be offered as one. See the governing reference.", "The drawing is to scale, and the scale, its basis and its tolerance are printed on every sheet.", "> The scale was derived from a dimension printed on the original architectural plan: two equal bays spanning 49.0 pixels are labelled 11 feet 8 inches, which gives 4.2 pixels per foot. A second reading agrees — at that scale the reception rooms compute to about 122 square feet against a printed label of about 125.", "> The tolerance is about three percent, which on this building is around two feet. That is immaterial for judging which zone a machine stands in, which is what this drawing is for. It is not adequate for construction, and every sheet is marked NOT FOR CONSTRUCTION accordingly.", "The overall building measures 75.8 feet by 67.1 feet, about 5,090 square feet, divided between the two units by a demising wall at the midpoint.", "The editable master and all three issued sheets are held as attachments to this record.", "> The master is a draw.io file. A drawing that can only be reissued by redrawing it is not a controlled drawing, so the master travels with the PDFs. It is attached to this record in the Reference Documents tab as a .drawio file, and is opened and edited at app.diagrams.net (File, Open From, Device) with nothing to install. After any change to the master, re-export ALL THREE sheets and replace all four attachments together, so the record never holds sheets that disagree with the drawing they came from.", "The SQF Practitioner shall review this drawing at least annually, and before that whenever equipment is moved, added or removed, whenever the rotation changes, and whenever the hygiene zoning is revised.", "> Equipment moving is the change most likely to happen and least likely to be reported, because moving a table does not feel like changing a controlled document."], "revision_history": "Rev New — drawn 2026-09-15, redrawn for a three-day rotation 2026-09-18. DRAFT. Not approved, not in force.\n\nWHY IT EXISTS. No controlled document in the set described the layout of the production floor or the route product takes across it. Nothing referenced a site plan, a floor plan or a product flow diagram, so the zoning the site works to existed only as practice. That matters more here than it would at most sites, because the rotation makes one floor area low risk on one day and high care on the next.\n\nHOW IT WAS BUILT. From the architectural floor plan for 415/425, traced to vector and set to a scale derived from a dimension printed on that plan. Equipment positions were measured from the marked-up plan rather than estimated, except for a small number of soft-edged label areas drawn as approximations and marked as such.\n\nTHE THREE-SHEET STRUCTURE IS THE POINT. The floor runs a three-day rotation and the equipment in the room differs on each day. Issuing a single sheet would show a floor that either exists a third of the time or never.\n\n2026-09-18 — TWO DAYS BECAME THREE. The drawing was first built for a two-day rotation, with dunking, sealing, packaging and lot coding all on Day 2. Production confirmed the finishing work is split: Day 2 is dunking in simple syrup and sealing, Day 3 is packaging, labelling, lot coding and bulk packaging. Sheet 2 was split into Sheets 2 and 3, the Day 3 equipment was placed by the owner, and the product route was renumbered so steps 1 to 9 still run end to end across the three sheets. Two facts came with it and are recorded in the procedure: sealed product is held overnight where the sealing unit stands on Day 2, and the weighing station is removed after Day 1. The second replaces an earlier statement that the weighing station stood idle inside HIGH CARE on Day 2; it does not.\n\nOPEN BEFORE ISSUE — ONE ITEM:\n\nTHE ZONE BOUNDARIES ARE NOT YET CONFIRMED ON THE FLOOR. They were derived from the identity and position of the equipment rather than from a walk of the building. The division itself is not in doubt — the oven is the kill step, upstream is low risk, downstream is high care — but where exactly the lines fall between the cooling racks, the mixers and the ovens on the west wall is the kind of thing that is settled by standing in the room. The SQF Practitioner confirms or corrects them, and the drawing issues on that confirmation.\n\nSCOPED OUT, AND NOT OMISSIONS:\n\nPersonnel flow, hand-wash points and allergen segregation. This drawing answers where equipment stands and where product goes. Personnel movement is a different question with a different review cycle, and three overlays on one sheet make all three harder to read. Control over personnel crossing the raw / high-care boundary belongs to the GMP programme, FSQM-012.\n\nSTATED LIMITATIONS, AND NOT DEFECTS:\n\nThe scale carries a tolerance of about three percent — around two feet on this building. That is immaterial for judging which zone a machine stands in and inadequate for construction, and every sheet is marked NOT FOR CONSTRUCTION. A single tape measurement of a known wall would remove it if the drawing is ever needed for another purpose.\n\nThe sheets are 11.31 by 12.61 inches, which is not a standard paper size and will scale if printed."}$patch$::jsonb
 where sop_number = 'FSQM-039';

do $verify$
declare r record; body text; bad text;
begin
  select status, revision, sqf_reference, sqf_required,
         jsonb_array_length(content->'procedure')   as lines,
         jsonb_array_length(content->'attachments') as files,
         content->>'governing_reference'            as gov,
         content
    into r
    from public.sop_documents where sop_number = 'FSQM-039';

  if r.status <> 'draft' or r.revision <> 'New' or r.sqf_reference is not null
     or r.sqf_required is not false then
    raise exception 'FSQM-039 lost its draft state or its no-clause position.';
  end if;
  if r.lines <> 30 then
    raise exception 'procedure is % lines, expected 30.', r.lines;
  end if;
  if r.files <> 3 then
    raise exception 'attachments changed (% files); this migration must not touch them.', r.files;
  end if;
  if r.gov not like '%WHAT IT IS NOT%' then
    raise exception 'governing_reference was disturbed.';
  end if;

  -- the working text must describe three days and nothing else
  body := concat_ws(' ', r.content->>'scope', r.content->>'records', r.content->>'definitions',
                    (r.content->'procedure')::text);
  foreach bad in array array['two-day', 'two sheets', 'both sheets', 'Steps 6 to 9',
                             'steps 6 to 9', 'idle equipment'] loop
    if body like '%' || bad || '%' then
      raise exception 'FSQM-039 still says "%".', bad;
    end if;
  end loop;
  if body not like '%three sheets%' or body not like '%Sheet 3 (Day 3)%'
     or body not like '%sealed product is held in its place%'
     or body not like '%weighing station is in the room on Day 1 only%' then
    raise exception 'FSQM-039 is missing part of the three-day text.';
  end if;
  if (r.content->>'revision_history') not like '%OPEN BEFORE ISSUE — ONE ITEM%'
     or (r.content->>'revision_history') not like '%TWO DAYS BECAME THREE%' then
    raise exception 'revision_history lost its open item or the 2026-09-18 note.';
  end if;

  raise notice 'FSQM-039: three-day text in place, % procedure lines, attachments untouched (%).',
    r.lines, r.files;
end $verify$;

commit;
