-- REP-007 - CAPA Log. D-07.
--
-- The register. FSQM-009 Part 9 calls it the answer to "show me your open corrective actions", and
-- it is the trending input 2.1.2.1 (iv) and 2.1.3.2 want. A derived report over FRM-007's responses
-- using the engine in src/lib/formReport.ts: type='report', NO entries of its own, so it does not
-- duplicate the Records page. Same pattern as REP-003 over FRM-002.
--
-- *** sourceStatus IS "all", NOT THE DEFAULT "submitted". *** This is the one decision on this
-- migration that could quietly break the deliverable. A CAPA is a draft entry for as long as it is
-- being worked - which is exactly the period a register exists to show. Under the default, an open
-- CAPA would be invisible until the day it closed, so the register would list only finished work
-- and answer the opposite of the question it is for. REP-003 uses "submitted" correctly, because a
-- complaint log lists complaints that have been filed; the two are genuinely different.
--
-- THE STATUS COLUMN IS A `cases` RULE AND ORDER MATTERS - first match wins:
--   closure_date is not empty                      -> Closed
--   verification_result = "Not effective ..."       -> Reopened
--   verification_result = "Effective ..."           -> Verified - awaiting closure
--   root_cause is not empty                         -> Under investigation
--   correction_taken is not empty                   -> Contained
--   otherwise                                       -> Open
-- Closed is tested first on purpose: a CAPA that was reopened and later closed is Closed, not
-- Reopened. All six states were driven through the real resolveReportColumns() before this was
-- written; none of them is assumed.
--
-- THE TWO `equals` VALUES ARE EXACT MATCHES ON FRM-007 SELECT OPTIONS, em dashes and all. That is
-- why FRM-007 and REP-007 are generated by ONE script from shared constants: authored separately, a
-- single changed word or dash on either side would break the column with no error anywhere - it
-- would simply always fall through to its default, and a register showing every CAPA as "Under
-- investigation" looks plausible enough to go unnoticed. The generator asserts every case value is
-- an option the source select actually offers, and that every column and param names a field
-- FRM-007 actually has.
--
-- NO FIXED filters[]. Every CAPA belongs on the register - unlike REP-201, which is an Approved
-- Supplier Register and must exclude the unapproved.
--
-- Inserted as status='draft'; approved and activated with FSQM-009 and FRM-007. Guarded on
-- non-existence, and on FRM-007 existing - a report whose source does not exist renders empty with
-- no error, which is the FSQM-022 Form-0010 failure in a different costume.

begin;

do $$
begin
  if exists (select 1 from public.sop_documents where sop_number = 'REP-007') then
    raise exception 'REP-007 already exists.';
  end if;
  if not exists (select 1 from public.sop_documents where sop_number = 'FRM-007') then
    raise exception 'FRM-007 does not exist - REP-007 projects from it. Apply 20260902000002 first.';
  end if;
end $$;

insert into public.sop_documents
  (sop_number, title, type, category, status, revision, sqf_reference, sqf_required, content)
values (
  'REP-007',
  'CAPA Log',
  'report',
  'Module 2',
  'draft',
  'New',
  '2.1.2.1, 2.1.3.2, 2.5.3.2, 2.5.4.4',
  true,
  jsonb_build_object('report_schema', $j007r$
{
  "version": 1,
  "sourceSopNumber": "FRM-007",
  "sourceStatus": "all",
  "defaultDateField": "date_raised",
  "columns": [
    {
      "id": "capa_no",
      "header": "CAPA No.",
      "source": {
        "kind": "field",
        "field": "capa_no"
      }
    },
    {
      "id": "raised",
      "header": "Raised",
      "source": {
        "kind": "field",
        "field": "date_raised"
      }
    },
    {
      "id": "source",
      "header": "Source",
      "source": {
        "kind": "field",
        "field": "source"
      }
    },
    {
      "id": "source_ref",
      "header": "Source ref",
      "source": {
        "kind": "field",
        "field": "source_ref"
      }
    },
    {
      "id": "severity",
      "header": "Severity",
      "source": {
        "kind": "field",
        "field": "severity"
      }
    },
    {
      "id": "summary",
      "header": "What happened",
      "source": {
        "kind": "field",
        "field": "description"
      }
    },
    {
      "id": "root_cause",
      "header": "Root cause",
      "source": {
        "kind": "field",
        "field": "root_cause"
      }
    },
    {
      "id": "owner",
      "header": "Owner",
      "source": {
        "kind": "field",
        "field": "capa_owner"
      }
    },
    {
      "id": "due",
      "header": "Target close",
      "source": {
        "kind": "field",
        "field": "target_close_date"
      }
    },
    {
      "id": "repeat",
      "header": "Repeat",
      "source": {
        "kind": "map",
        "field": "is_repeat",
        "map": {
          "true": "Yes",
          "false": "",
          "Yes": "Yes",
          "No": ""
        },
        "fallback": ""
      }
    },
    {
      "id": "status",
      "header": "Status",
      "source": {
        "kind": "cases",
        "default": "Open",
        "cases": [
          {
            "field": "closure_date",
            "op": "notEmpty",
            "then": "Closed"
          },
          {
            "field": "verification_result",
            "op": "equals",
            "value": "Not effective — reopen the investigation",
            "then": "Reopened"
          },
          {
            "field": "verification_result",
            "op": "equals",
            "value": "Effective — no further action",
            "then": "Verified - awaiting closure"
          },
          {
            "field": "root_cause",
            "op": "notEmpty",
            "then": "Under investigation"
          },
          {
            "field": "correction_taken",
            "op": "notEmpty",
            "then": "Contained"
          }
        ]
      }
    },
    {
      "id": "closed",
      "header": "Closed",
      "source": {
        "kind": "field",
        "field": "closure_date"
      }
    }
  ],
  "params": [
    {
      "id": "raised_between",
      "label": "Raised between",
      "type": "date-range",
      "field": "date_raised"
    },
    {
      "id": "status",
      "label": "Status",
      "type": "select",
      "column": "status"
    },
    {
      "id": "source",
      "label": "Source",
      "type": "select",
      "column": "source"
    },
    {
      "id": "severity",
      "label": "Severity",
      "type": "select",
      "column": "severity"
    }
  ],
  "legend": [
    "Every corrective and preventive action raised under FSQM-009, from any source. Open entries appear as soon as they are raised - the register is not limited to closed items.",
    "Status: Open, Contained, Under investigation, Verified - awaiting closure, Reopened, Closed. A CAPA closes only when effectiveness has been verified (FSQM-009 Parts 7 and 8).",
    "Retained a minimum of two years, or shelf life plus twelve months where longer; permanently for a CAPA relating to a withdrawal or recall."
  ]
}
$j007r$::jsonb, 'attachments', '[]'::jsonb)
);

do $$
declare
  r record;
begin
  select status, type,
         content->'report_schema'->>'sourceSopNumber'                        as src,
         content->'report_schema'->>'sourceStatus'                           as src_status,
         content->'report_schema'->>'defaultDateField'                       as date_field,
         jsonb_array_length(content->'report_schema'->'columns')             as cols,
         jsonb_array_length(content->'report_schema'->'params')              as params,
         jsonb_array_length(content->'report_schema'->'legend')              as legend,
         (select jsonb_array_length(c->'source'->'cases')
            from jsonb_array_elements(content->'report_schema'->'columns') c
           where c->>'id' = 'status')                                        as status_cases,
         (select c->'source'->'cases'->0->>'field'
            from jsonb_array_elements(content->'report_schema'->'columns') c
           where c->>'id' = 'status')                                        as first_case
    into r
    from public.sop_documents where sop_number = 'REP-007';

  if r.status <> 'draft' or r.type <> 'report' then
    raise exception 'REP-007 wrong metadata: status=%, type=%.', r.status, r.type;
  end if;
  if r.src <> 'FRM-007' then
    raise exception 'REP-007 sources from % rather than FRM-007.', r.src;
  end if;
  -- the decision this whole migration turns on
  if r.src_status is distinct from 'all' then
    raise exception 'REP-007 sourceStatus is % - open CAPAs would be invisible until closed.',
      coalesce(r.src_status, 'unset (defaults to submitted)');
  end if;
  if r.cols <> 12 or r.params <> 4 or r.legend <> 3 then
    raise exception 'REP-007 wrong shape: % columns, % params, % legend lines (expected 12 / 4 / 3).',
      r.cols, r.params, r.legend;
  end if;
  if r.date_field <> 'date_raised' then
    raise exception 'REP-007 defaultDateField is %, expected date_raised.', r.date_field;
  end if;
  -- Closed must be tested first: a reopened-then-closed CAPA is Closed, not Reopened
  if r.status_cases <> 5 or r.first_case <> 'closure_date' then
    raise exception 'REP-007 status rules wrong: % cases, first tests % (expected 5 / closure_date).',
      r.status_cases, r.first_case;
  end if;
end $$;

commit;
