// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsukaixinoqmggpxxonn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzdWthaXhpbm9xbWdncHh4b25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTQ5NzksImV4cCI6MjA4ODczMDk3OX0.Wh2Etaz8I5EB-LNSL7FYp_ruVsonMeQRqEbB7L1Ed40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});